export const myProject = [{
  name: 'Gamehub',
  summary: "Gamehub is a single-page application (SPA) that I conceived and developed entirely on my own. As a personal project aimed at demonstrating proficiency in the MERN stack, Gamehub draws inspiration from platforms like Steam. Leveraging both front-end and back-end technologies, I engineered this platform from the ground up to ensure a smooth and immersive shopping experience for users.",
  description: "Gamehub is a personal project developed to showcase proficiency in the MERN stack. Inspired by platforms like Steam, I aimed to create a similar experience while adding unique functionalities. As a single-page application (SPA), Gamehub simulates an online store for video games, providing users with a platform to browse, explore, and interact with game listings. Leveraging React for the front-end and Express.js for the back-end, Gamehub implements robust user authentication using JSON Web Tokens (JWT) and ensures secure password hashing with bcrypt. MongoDB serves as the database, facilitating dynamic inventory management through change streams, allowing real-time updates to game availability.\n\nKey features of Gamehub include an interactive game catalog, user account management with distinct privileges for gamers and developers, and responsive cart functionality for seamless browsing and purchasing experiences. The platform prioritizes usability and responsiveness, with an intuitive interface designed to guide users through the browsing and purchasing process effortlessly. Throughout the development process, my biggest struggle and reward was building the search bar and logic from scratch, a challenge that ultimately contributed to the platform's unique functionality and my growth as a developer.\n\nI invite you to explore Gamehub and experience the culmination of my efforts. Building this project has been an immensely rewarding journey, and I'm excited to share it with you. You can visit the Live link for the website or check out the code by clicking on the Code Link.",
  tech: "HTML, CSS, JavaScript, React, MongoDB, ExpressJS, NodeJS, Git, Heroku",
  projectLink: 'https://github.com/lucas9121/Gamehub',
  liveLink: 'https://gamehub-react.herokuapp.com/games',
  color: '#007bff',
  images: [],
},
{
  name: "Psych Byte",
  summary: "Psych Bite is an application that sends an email every morning based off 3 authors revolving around finance, psychology and faith. People can add their email on the website to receive one adn unsubscribe in the link on the email.",
  description: "",
  tech: "MongoDB, React, NodeJS, ExpressJS, Nodemailer, Git, Heroku",
  projectLink: "https://github.com/lucas9121/favorite-quotes",
  liveLink: "https://psych-bite.herokuapp.com/",
  color: "green",
  images: [],
},
{
  name: "Meals To Go",
  summary: "",
  description: "",
  tech: "",
  projectLink: "",
  liveLink: "",
  color: "",
  images: [],
},
{
  name: "Roaming Spoon",
  summary: "The Roaming spoon was a group project built in collaboration with a UX team. In the full-stack role, I helped connect the back-end to the front-end and build the search page. Discover amazing food trucks in your area using the Roaming Spoon app! Use The Roaming Spoon to search your favorite food trucks and see their current location. Find out more information for any food truck like location, phone number, business hours, and reviews.",
  description: "",
  tech: "HTML, CSS, JavaScript, Google, React, Bootstrap, NodeJS, MongoDB",
  projectLink: "",
  liveLink: "",
  color: "",
  images: [],
},
{
  name: "Wars of Volgrora",
  summary: "",
  description: "",
  tech: "",
  projectLink: "",
  liveLink: "",
  color: "",
  images: [],
},
{
  name: "",
  summary: "",
  description: "",
  tech: "",
  projectLink: "",
  liveLink: "",
  color: "",
  images: [],
},]
